// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-operations/CommandCenter.tsx": () => import("../components/mockups/dashboard-operations/CommandCenter.tsx"),
  "./components/mockups/dashboard-operations/CompactOperations.tsx": () => import("../components/mockups/dashboard-operations/CompactOperations.tsx"),
  "./components/mockups/dashboard-operations/Current.tsx": () => import("../components/mockups/dashboard-operations/Current.tsx"),
  "./components/mockups/dashboard-operations/UnifiedPriorityQueue.tsx": () => import("../components/mockups/dashboard-operations/UnifiedPriorityQueue.tsx")
};
