import type { FieldDef, FormId } from "./types";

const ALL: FormId[] = [
  "academic_year_tutoring",
  "summer_tutoring",
  "first_class",
  "express",
  "summer_master_class",
];

const TUTORING: FormId[] = ["academic_year_tutoring", "summer_tutoring"];
const COURSES: FormId[] = ["first_class", "express", "summer_master_class"];

/** Verified structured and key free-text fields across the five Gravity Forms. */
export const FIELD_CATALOG: FieldDef[] = [
  {
    id: "student_name",
    label: "Student name",
    control: "text",
    owner: "student",
    forms: ALL,
    required: true,
    mapsTo: "students.firstName + students.lastName",
  },
  {
    id: "gender",
    label: "Gender",
    control: "radio",
    owner: "student",
    forms: ALL,
    required: "pending",
    optionListId: "GENDER",
    mapsTo: "students.gender",
  },
  {
    id: "school",
    label: "School",
    control: "text",
    owner: "student",
    forms: ALL,
    required: true,
    mapsTo: "students.schoolName",
    notes: "Canonical school lookup + suggest path later",
  },
  {
    id: "grade",
    label: "Grade",
    control: "select",
    owner: "student",
    forms: ALL,
    required: true,
    optionListId: "GRADE_LABELS",
    mapsTo: "students.gradeLabel",
  },
  {
    id: "graduation_year",
    label: "Graduation year",
    control: "select",
    owner: "student",
    forms: ALL,
    required: true,
    optionListId: "GRADUATION_YEARS",
    mapsTo: "students.graduationYear",
  },
  {
    id: "birthdate",
    label: "Birthdate",
    control: "restricted",
    owner: "restricted",
    forms: ALL,
    required: "pending",
    mapsTo: "students.birthdate",
  },
  {
    id: "student_cell",
    label: "Student cell phone",
    control: "text",
    owner: "student",
    forms: ALL,
    required: "pending",
    mapsTo: "students.cellPhone",
  },
  {
    id: "student_email",
    label: "Student email",
    control: "text",
    owner: "student",
    forms: ALL,
    required: "pending",
    mapsTo: "students.email",
  },
  {
    id: "other_support_info",
    label: "Other information (504 / IEP / accommodations)",
    control: "restricted",
    owner: "restricted",
    forms: ALL,
    required: "pending",
    mapsTo: "students.supportNotesRestricted",
  },
  {
    id: "college_board_accommodations",
    label: "College Board approved accommodations",
    control: "radio",
    owner: "restricted",
    forms: COURSES,
    required: true,
    optionListId: "YES_NO_PENDING",
  },
  {
    id: "act_accommodations",
    label: "ACT Org. approved accommodations",
    control: "radio",
    owner: "restricted",
    forms: COURSES,
    required: true,
    optionListId: "YES_NO_PENDING",
  },
  {
    id: "accommodation_detail",
    label: "Specify accommodations",
    control: "restricted",
    owner: "restricted",
    forms: COURSES,
    required: "pending",
  },
  {
    id: "household_address",
    label: "Primary / student address",
    control: "text",
    owner: "household",
    forms: ALL,
    required: true,
    mapsTo: "households.addressLine1 + city + state + postalCode",
  },
  {
    id: "household_state",
    label: "State",
    control: "select",
    owner: "household",
    forms: ALL,
    required: true,
    optionListId: "US_STATES",
    mapsTo: "households.state",
  },
  {
    id: "parent1_contact",
    label: "Parent 1 contact set",
    control: "text",
    owner: "guardian",
    forms: ALL,
    required: true,
    mapsTo: "guardians",
  },
  {
    id: "parent2_contact",
    label: "Parent 2 contact set",
    control: "text",
    owner: "guardian",
    forms: ALL,
    required: true,
    mapsTo: "guardians (second)",
  },
  {
    id: "billing_contact",
    label: "Billing name / email / phone",
    control: "text",
    owner: "billingIntent",
    forms: ALL,
    required: true,
    mapsTo: "households.billingOwnerGuardianId",
  },
  {
    id: "referral_source",
    label: "How did you hear about us?",
    control: "select",
    owner: "tutoringRequest",
    forms: ALL,
    required: true,
    optionListId: "REFERRAL_SOURCE",
  },
  {
    id: "subjects",
    label: "Subject(s)",
    control: "checkbox_group",
    owner: "tutoringRequest",
    forms: TUTORING,
    required: true,
    optionListId: "ACADEMIC_SUBJECTS",
  },
  {
    id: "subject_notes",
    label: "Subject notes / other subjects",
    control: "textarea",
    owner: "tutoringRequest",
    forms: TUTORING,
    required: "pending",
  },
  {
    id: "test_prep_interests",
    label: "Tutoring test prep",
    control: "checkbox_group",
    owner: "tutoringRequest",
    forms: TUTORING,
    required: "pending",
    optionListId: "TEST_PREP_INTERESTS",
  },
  {
    id: "academic_schedule_windows",
    label: "Preferred schedule (day & time)",
    control: "checkbox_group",
    owner: "tutoringRequest",
    forms: ["academic_year_tutoring"],
    required: true,
    optionListId: "ACADEMIC_SCHEDULE_WINDOWS",
  },
  {
    id: "summer_schedule_windows",
    label: "Tutoring days and times",
    control: "checkbox_group",
    owner: "tutoringRequest",
    forms: ["summer_tutoring"],
    required: true,
    optionListId: "SUMMER_SCHEDULE_WINDOWS",
  },
  {
    id: "summer_date_range",
    label: "Start / end date",
    control: "text",
    owner: "tutoringRequest",
    forms: ["summer_tutoring"],
    required: true,
  },
  {
    id: "schedule_notes",
    label: "Other schedule notes",
    control: "textarea",
    owner: "tutoringRequest",
    forms: ["summer_tutoring"],
    required: true,
  },
  {
    id: "academic_rate_package",
    label: "Hours/rates (standard)",
    control: "radio",
    owner: "billingIntent",
    forms: ["academic_year_tutoring"],
    required: "pending",
    optionListId: "ACADEMIC_RATE_PACKAGES",
  },
  {
    id: "academic_advanced_rate_package",
    label: "Hours/rates (advanced)",
    control: "radio",
    owner: "billingIntent",
    forms: ["academic_year_tutoring"],
    required: "pending",
    optionListId: "ACADEMIC_ADVANCED_RATE_PACKAGES",
  },
  {
    id: "academic_payment_plan",
    label: "Payment plan",
    control: "radio",
    owner: "billingIntent",
    forms: ["academic_year_tutoring"],
    required: true,
    optionListId: "ACADEMIC_PAYMENT_PLANS",
  },
  {
    id: "summer_payment_plan",
    label: "Payment plan",
    control: "radio",
    owner: "billingIntent",
    forms: ["summer_tutoring"],
    required: true,
    optionListId: "SUMMER_PAYMENT_PLANS",
  },
  {
    id: "first_class_time_slot",
    label: "Time slot preference",
    control: "radio",
    owner: "courseEnrollment",
    forms: ["first_class"],
    required: true,
    optionListId: "FIRST_CLASS_TIME_SLOTS",
  },
  {
    id: "express_time_slot",
    label: "Express time slot preference",
    control: "radio",
    owner: "courseEnrollment",
    forms: ["express"],
    required: "pending",
    optionListId: "EXPRESS_TIME_SLOTS",
    notes: "Not observed on live form — pendingClientConfirmation",
  },
  {
    id: "master_class_sessions",
    label: "Class sessions",
    control: "checkbox_group",
    owner: "courseEnrollment",
    forms: ["summer_master_class"],
    required: true,
    optionListId: "MASTER_CLASS_SESSIONS",
  },
  {
    id: "first_class_payment_plan",
    label: "Paying in full or monthly",
    control: "radio",
    owner: "billingIntent",
    forms: ["first_class"],
    required: true,
    optionListId: "FIRST_CLASS_PAYMENT_PLANS",
  },
  {
    id: "express_payment_plan",
    label: "Paying in full or monthly",
    control: "radio",
    owner: "billingIntent",
    forms: ["express"],
    required: true,
    optionListId: "EXPRESS_PAYMENT_PLANS",
  },
  {
    id: "master_class_payment_plan",
    label: "Paying in full or monthly",
    control: "radio",
    owner: "billingIntent",
    forms: ["summer_master_class"],
    required: true,
    optionListId: "MASTER_CLASS_PAYMENT_PLANS",
  },
  {
    id: "auto_charge",
    label: "Automatically charge credit card for monthly payment",
    control: "radio",
    owner: "billingIntent",
    forms: ALL,
    required: "pending",
    optionListId: "YES_NO",
  },
  {
    id: "alt_payment_method",
    label: "Alternative form of payment",
    control: "radio",
    owner: "billingIntent",
    forms: ALL,
    required: "pending",
    optionListId: "ALT_PAYMENT_METHODS",
  },
  {
    id: "policy_ack",
    label: "Policy / course information acknowledgement",
    control: "acknowledgement",
    owner: "consent",
    forms: ALL,
    required: true,
  },
  {
    id: "consent_agreement",
    label: "I agree to the terms outlined in this Agreement",
    control: "acknowledgement",
    owner: "consent",
    forms: ALL,
    required: true,
  },
  {
    id: "learning_needs",
    label: "Subjects or learning goals",
    control: "textarea",
    owner: "student",
    forms: [],
    required: true,
    mapsTo: "students.learningNeeds",
    notes: "App Add Student field (non-restricted); not a Gravity multi-select",
  },
];

export function fieldsForForm(formId: FormId): FieldDef[] {
  return FIELD_CATALOG.filter((field) => field.forms.includes(formId));
}

export function getField(id: string): FieldDef | undefined {
  return FIELD_CATALOG.find((field) => field.id === id);
}
